// <auto-generated />
using System;
using FindMyCountry.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FindMyCountry.Migrations
{
    [DbContext(typeof(FindMyCountryContextDB))]
    [Migration("20260501103341_InitCity")]
    partial class InitCity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FindMyCountry.shared.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("cId")
                        .HasColumnType("int");

                    b.Property<string>("cityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("countryCId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("countryCId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("FindMyCountry.shared.Country", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CId"));

                    b.Property<int?>("countryCode")
                        .HasColumnType("int");

                    b.Property<string>("countryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("FindMyCountry.shared.City", b =>
                {
                    b.HasOne("FindMyCountry.shared.Country", "country")
                        .WithMany()
                        .HasForeignKey("countryCId");

                    b.Navigation("country");
                });
#pragma warning restore 612, 618
        }
    }
}
